from .star_ultimate_converter import NODE_CLASS_MAPPINGS as CONVERTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_DISPLAY_NAME_MAPPINGS
from .starnodes_aio_splitter import NODE_CLASS_MAPPINGS as SPLITTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPLITTER_DISPLAY_NAME_MAPPINGS
from .starnodes_aio_saver import NODE_CLASS_MAPPINGS as SAVER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SAVER_DISPLAY_NAME_MAPPINGS
from .star_model_layers_info import NODE_CLASS_MAPPINGS as LAYERS_INFO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LAYERS_INFO_DISPLAY

NODE_CLASS_MAPPINGS = {
    **CONVERTER_CLASS_MAPPINGS, 
    **SPLITTER_CLASS_MAPPINGS,
    **SAVER_CLASS_MAPPINGS,
    **LAYERS_INFO_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CONVERTER_DISPLAY_NAME_MAPPINGS, 
    **SPLITTER_DISPLAY_NAME_MAPPINGS,
    **SAVER_DISPLAY_NAME_MAPPINGS,
    **LAYERS_INFO_DISPLAY
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
