from .star_ultimate_converter import NODE_CLASS_MAPPINGS as CONVERTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_DISPLAY_NAME_MAPPINGS
from .starnodes_aio_splitter import NODE_CLASS_MAPPINGS as SPLITTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPLITTER_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**CONVERTER_CLASS_MAPPINGS, **SPLITTER_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CONVERTER_DISPLAY_NAME_MAPPINGS, **SPLITTER_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
