from .star_ultimate_converter import NODE_CLASS_MAPPINGS as CONVERTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_DISPLAY_NAME_MAPPINGS
from .starnodes_aio_splitter import NODE_CLASS_MAPPINGS as SPLITTER_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPLITTER_DISPLAY_NAME_MAPPINGS
from .star_model_layers_info import NODE_CLASS_MAPPINGS as LAYERS_INFO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LAYERS_INFO_DISPLAY
from .star_model_converter_pro import NODE_CLASS_MAPPINGS as CONVERTER_PRO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CONVERTER_PRO_DISPLAY

# Import API routes for profile metadata endpoint
try:
    from . import api_routes
except Exception as e:
    print(f"[StarNodes] Warning: Could not load API routes: {e}")

NODE_CLASS_MAPPINGS = {
    **CONVERTER_CLASS_MAPPINGS, 
    **SPLITTER_CLASS_MAPPINGS,
    **LAYERS_INFO_MAPPINGS,
    **CONVERTER_PRO_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CONVERTER_DISPLAY_NAME_MAPPINGS, 
    **SPLITTER_DISPLAY_NAME_MAPPINGS,
    **LAYERS_INFO_DISPLAY,
    **CONVERTER_PRO_DISPLAY
}

# HIER IST DER FEHLENDE TEIL:
# Teile ComfyUI mit, wo die Frontend-Skripte liegen
WEB_DIRECTORY = "./web"

# Füge WEB_DIRECTORY zur Export-Liste hinzu
__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS', 'WEB_DIRECTORY']
